#!/bin/sh
# Requires pdftohtml inotifywait

## Ugly bookkeeping
WATCH="$XDG_RUNTIME_DIR/doc"
rm "$WATCH"/ctl
mkdir -p "$WATCH"
mkfifo -m 600 -- "$WATCH"/ctl

create() {
	title="$(basename "$1")"
	mkdir -p "$WATCH/$title"
	case "$(file -biL "$1")" in
		*pdf*) pdftohtml "$1" "$WATCH/$title/$title.html" & ;;
		#*djvu*)
		*epub*) unzip -d "$WATCH/$title" "$1" & ;;
	esac
}

# Monitor our ctlfile
tail -f "$WATCH"/ctl | while read -r name; do
	case "$name" in
		open*) test -d "$WATCH/$(basename "${name#open\ *}")" || create "${name#open\ *}" ;;
		quit|exit) break ;;
	esac
done